# MacOS X and Linux builds of Kitematic
# See e.g. https://github.com/travis-ci/travis-ci/issues/2311
sudo: false

language: node_js

node_js:
  - '4.1.1'

os:
  - linux
  - osx

matrix:
  fast_finish: true

cache:
  directories:
    - node_modules

install:
  - npm install
  #- npm test
  - npm run release-verbose

before_install:
  - node --version
  - npm --version
