# appveyor file
# https://www.appveyor.com/docs/appveyor-yml/

version: "{build}"

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - ps: Install-Product node 4
  - cmd: node --version
  - cmd: npm --version

platform:
  - x86
  - x64

install:
  #- cmd: SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  #- cmd: SET PATH=C:\python27;%PATH%
  - cmd: npm install
  - cmd: npm run release-verbose

branches:
  only:
    - master

artifacts:
  - path: "release\*.zip"
    name: AppRelease
    type: Auto

# disable build and test pahses
build: off
test: off